-- MySQL Script generated by MySQL Workbench
-- Sat May 12 03:58:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Framakollect
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Framakollect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Framakollect` DEFAULT CHARACTER SET utf8 ;
USE `Framakollect` ;

-- -----------------------------------------------------
-- Table `Framakollect`.`medicament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`medicament` (
  `id_med` INT(11) NOT NULL AUTO_INCREMENT,
  `MED_DEPOTLEGAL` VARCHAR(9) NULL DEFAULT NULL,
  `MED_NOMCOMMERCIAL` VARCHAR(19) NULL DEFAULT NULL,
  `MED_COMPOSITION` VARCHAR(80) NULL DEFAULT NULL,
  `MED_EFFETS` VARCHAR(194) NULL DEFAULT NULL,
  `MED_CONTREINDIC` VARCHAR(236) NULL DEFAULT NULL,
  `FAM_CODE` VARCHAR(3) NULL,
  PRIMARY KEY (`id_med`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framakollect`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`commande` (
  `id_commande` INT(11) NOT NULL AUTO_INCREMENT,
  `med_depotLEGAL` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `fam_code` VARCHAR(3) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `med_nomcommercial` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nb_med_commande` INT(11) NOT NULL,
  `total_prixHT` DECIMAL NOT NULL,
  `id_med` INT(11) NULL,
  PRIMARY KEY (`id_commande`),
  INDEX `fk_commande_medicament1_idx` (`id_med` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Framakollect`.`famille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`famille` (
  `id_fam` INT(11) NOT NULL AUTO_INCREMENT,
  `FAM_CODE` VARCHAR(3) NULL DEFAULT NULL,
  `FAM_LIBELLE` VARCHAR(67) NULL DEFAULT NULL,
  `medicament_id_med` INT(11) NULL,
  PRIMARY KEY (`id_fam`),
  INDEX `fk_famille_medicament1_idx` (`medicament_id_med` ASC),
  CONSTRAINT `fk_famille_medicament1`
    FOREIGN KEY (`medicament_id_med`)
    REFERENCES `Framakollect`.`medicament` (`id_med`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framakollect`.`med_prixht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`med_prixht` (
  `med_depotLEGAL` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `med_nomcommercial` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `prix_medHT` DECIMAL NOT NULL,
  `id_prix` INT NOT NULL AUTO_INCREMENT,
  `id_med` INT(11) NULL,
  PRIMARY KEY (`id_prix`),
  INDEX `fk_med_prixht_medicament1_idx` (`id_med` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Framakollect`.`med_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`med_stock` (
  `med_depotLEGAL` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `med_nomcommercial` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nb_stock` INT(11) NOT NULL,
  `id_med` INT(11) NULL,
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_med_stock_medicament1_idx` (`id_med` ASC),
  PRIMARY KEY (`id_stock`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Framakollect`.`Acces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`Acces` (
  `idAcces` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idAcces`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Framakollect`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`membre` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `idAcces` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_membre_Acces1_idx` (`idAcces` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Framakollect`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`region` (
  `id_reg` INT(11) NOT NULL AUTO_INCREMENT,
  `REG_CODE` VARCHAR(2) NULL DEFAULT NULL,
  `SEC_CODE` VARCHAR(1) NULL DEFAULT NULL,
  `REG_NOM` VARCHAR(26) NULL DEFAULT NULL,
  PRIMARY KEY (`id_reg`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framakollect`.`praticien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`praticien` (
  `PRA_NUM` INT(2) NOT NULL AUTO_INCREMENT,
  `PRA_NOM` VARCHAR(16) NULL DEFAULT NULL,
  `PRA_PRENOM` VARCHAR(15) NULL DEFAULT NULL,
  `PRA_ADRESSE` VARCHAR(29) NULL DEFAULT NULL,
  `PRA_CP` INT(5) NULL DEFAULT NULL,
  `PRA_VILLE` VARCHAR(19) NULL DEFAULT NULL,
  `PRA_COEFNOTORIETE` VARCHAR(11) NULL DEFAULT NULL,
  `TYP_CODE` VARCHAR(2) NULL DEFAULT NULL,
  `id_reg` INT(11) NULL,
  PRIMARY KEY (`PRA_NUM`),
  INDEX `fk_praticien_region1_idx` (`id_reg` ASC),
  CONSTRAINT `fk_praticien_region1`
    FOREIGN KEY (`id_reg`)
    REFERENCES `Framakollect`.`region` (`id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framakollect`.`proposer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`proposer` (
  `v_num` INT(11) NOT NULL,
  `ech_num` INT(11) NOT NULL,
  PRIMARY KEY (`v_num`, `ech_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Framakollect`.`specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`specialite` (
  `id_spe` INT(11) NOT NULL AUTO_INCREMENT,
  `TYP_CODE` VARCHAR(2) NULL DEFAULT NULL,
  `TYP_LIBELLE` VARCHAR(22) NULL DEFAULT NULL,
  `TYP_LIEU` VARCHAR(19) NULL DEFAULT NULL,
  PRIMARY KEY (`id_spe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framakollect`.`visite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`visite` (
  `V_NUM` INT(11) NOT NULL AUTO_INCREMENT,
  `V_DATE` VARCHAR(10) NULL DEFAULT NULL,
  `V_DESCRIPTION` VARCHAR(90) NULL DEFAULT NULL,
  `PRA_NUM` INT(2) NULL,
  PRIMARY KEY (`V_NUM`),
  INDEX `fk_visite_praticien1_idx` (`PRA_NUM` ASC),
  CONSTRAINT `fk_visite_praticien1`
    FOREIGN KEY (`PRA_NUM`)
    REFERENCES `Framakollect`.`praticien` (`PRA_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Framakollect`.`visiteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Framakollect`.`visiteur` (
  `id_visiteur` INT(11) NOT NULL AUTO_INCREMENT,
  `VIS_MATRICULE` VARCHAR(4) NULL DEFAULT NULL,
  `VIS_NOM` VARCHAR(15) NULL DEFAULT NULL,
  `Vis_PRENOM` VARCHAR(12) NULL DEFAULT NULL,
  `VIS_ADRESSE` VARCHAR(31) NULL DEFAULT NULL,
  `VIS_CP` VARCHAR(5) NULL DEFAULT NULL,
  `VIS_VILLE` VARCHAR(19) NULL DEFAULT NULL,
  `VIS_DATEEMBAUCHE` VARCHAR(10) NULL DEFAULT NULL,
  `V_NUM` INT(11) NULL,
  `id_spe` INT(11) NULL,
  PRIMARY KEY (`id_visiteur`),
  INDEX `fk_visiteur_visite1_idx` (`V_NUM` ASC),
  INDEX `fk_visiteur_specialite1_idx` (`id_spe` ASC),
  CONSTRAINT `fk_visiteur_visite1`
    FOREIGN KEY (`V_NUM`)
    REFERENCES `Framakollect`.`visite` (`V_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visiteur_specialite1`
    FOREIGN KEY (`id_spe`)
    REFERENCES `Framakollect`.`specialite` (`id_spe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
