-- MySQL Script generated by MySQL Workbench
-- Mon May  7 16:45:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Accès`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accès` (
  `idAccès` INT(11) NOT NULL,
  `libelle_ac` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idAccès`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `Id_utilisateur` INT(11) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `email_utilisateur` VARCHAR(30) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `IdAccès` INT(11) NOT NULL,
  PRIMARY KEY (`Id_utilisateur`),
  INDEX `IdAccès_idx` (`IdAccès` ASC),
  CONSTRAINT `IdAccès`
    FOREIGN KEY (`IdAccès`)
    REFERENCES `mydb`.`Accès` (`idAccès`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne` (
  `Id_Personne` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `numPortable` VARCHAR(10) NOT NULL,
  `numFixe` VARCHAR(10) NOT NULL,
  `adresse` VARCHAR(35) NOT NULL,
  `codePostale` VARCHAR(5) NULL,
  `ville` VARCHAR(20) NULL,
  PRIMARY KEY (`Id_Personne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pere` (
  `Id_pere` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(11) NULL,
  `Id_Personne` INT NOT NULL,
  PRIMARY KEY (`Id_pere`),
  INDEX `fk_Pere_Personne1_idx` (`Id_Personne` ASC),
  CONSTRAINT `fk_Pere_Personne1`
    FOREIGN KEY (`Id_Personne`)
    REFERENCES `mydb`.`Personne` (`Id_Personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mere` (
  `Id_mere` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(11) NULL,
  `Id_Personne` INT NOT NULL,
  PRIMARY KEY (`Id_mere`),
  INDEX `fk_Mere_Personne1_idx` (`Id_Personne` ASC),
  CONSTRAINT `fk_Mere_Personne1`
    FOREIGN KEY (`Id_Personne`)
    REFERENCES `mydb`.`Personne` (`Id_Personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Joueur` (
  `Id_joueur` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Id_Personne` INT NOT NULL,
  `Pere_Id_pere` INT NOT NULL,
  `Mere_Id_mere` INT NOT NULL,
  PRIMARY KEY (`Id_joueur`),
  INDEX `fk_Joueur_Personne1_idx` (`Id_Personne` ASC),
  INDEX `fk_Joueur_Pere1_idx` (`Pere_Id_pere` ASC),
  INDEX `fk_Joueur_Mere1_idx` (`Mere_Id_mere` ASC),
  CONSTRAINT `fk_Joueur_Personne1`
    FOREIGN KEY (`Id_Personne`)
    REFERENCES `mydb`.`Personne` (`Id_Personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Joueur_Pere1`
    FOREIGN KEY (`Pere_Id_pere`)
    REFERENCES `mydb`.`Pere` (`Id_pere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Joueur_Mere1`
    FOREIGN KEY (`Mere_Id_mere`)
    REFERENCES `mydb`.`Mere` (`Id_mere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saison` (
  `libelle_saison` INT NOT NULL,
  `Id_saison` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Id_saison`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Licence` (
  `Id_licence` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_licence` VARCHAR(30) NOT NULL,
  `categorie_licence` VARCHAR(30) NOT NULL,
  `date` DATE NOT NULL,
  `renouvellement_licence` VARCHAR(30) NOT NULL,
  `num_licence` VARCHAR(30) NOT NULL,
  `Id_joueur` INT(11) NOT NULL,
  `Id_saison` INT NOT NULL,
  PRIMARY KEY (`Id_licence`),
  INDEX `fk_licence_Joueur1_idx` (`Id_joueur` ASC),
  INDEX `fk_Licence_Saison1_idx` (`Id_saison` ASC),
  CONSTRAINT `fk_licence_Joueur1`
    FOREIGN KEY (`Id_joueur`)
    REFERENCES `mydb`.`Joueur` (`Id_joueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Licence_Saison1`
    FOREIGN KEY (`Id_saison`)
    REFERENCES `mydb`.`Saison` (`Id_saison`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PhotoJoueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PhotoJoueur` (
  `Id_Photo` INT(11) NOT NULL,
  `Image_type` VARCHAR(5) NULL,
  `Image_href` VARCHAR(30) NOT NULL,
  `Id_joueur` INT(11) NOT NULL,
  PRIMARY KEY (`Id_Photo`),
  INDEX `fk_PhotoJoueur_Joueur1_idx` (`Id_joueur` ASC),
  CONSTRAINT `fk_PhotoJoueur_Joueur1`
    FOREIGN KEY (`Id_joueur`)
    REFERENCES `mydb`.`Joueur` (`Id_joueur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paiement` (
  `Id_Paiement` INT NOT NULL AUTO_INCREMENT,
  `Attente_Paiement` VARCHAR(30) NOT NULL,
  `Cotisation_Paiement` VARCHAR(30) NOT NULL,
  `Depot` VARCHAR(30) NOT NULL,
  `Numere_Cheque_Paiement` VARCHAR(15) NOT NULL,
  `Id_licence` INT(11) NOT NULL,
  PRIMARY KEY (`Id_Paiement`),
  INDEX `fk_Paiement_Licence1_idx` (`Id_licence` ASC),
  CONSTRAINT `fk_Paiement_Licence1`
    FOREIGN KEY (`Id_licence`)
    REFERENCES `mydb`.`Licence` (`Id_licence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EtatFinancier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EtatFinancier` (
  `Id_EtatFinancier` INT NOT NULL,
  `FinancierPayer` INT NOT NULL,
  `FInancier_a_payer` INT NOT NULL,
  `Paiement_Final` INT NOT NULL,
  PRIMARY KEY (`Id_EtatFinancier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avoir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avoir` (
  `Id_Avoir` INT NOT NULL AUTO_INCREMENT,
  `Id_Paiement` INT NOT NULL,
  `Id_EtatFinancier` INT NOT NULL,
  PRIMARY KEY (`Id_Avoir`),
  INDEX `Id_Paiement_idx` (`Id_Paiement` ASC),
  INDEX `fk_Avoir_ControleFinancier1_idx` (`Id_EtatFinancier` ASC),
  CONSTRAINT `Id_Paiement`
    FOREIGN KEY (`Id_Paiement`)
    REFERENCES `mydb`.`Paiement` (`Id_Paiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avoir_ControleFinancier1`
    FOREIGN KEY (`Id_EtatFinancier`)
    REFERENCES `mydb`.`EtatFinancier` (`Id_EtatFinancier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
